### ISSUE TITLE
Is the pretrained model correct?

### ISSUE THREAD

**Issue by nmfisher** [keonlee9420/Daft-Exprt#7]
I've downloaded the file @ https://drive.google.com/drive/folders/1rmeW24lrCg_qwPkVI0D4bRNq4HSv_4rE
but can't manage to get the model to load, on either the master branch or the v1.0.0 zip file.

I get the following error on v1.0.0
```
Unexpected key(s) in state_dict: "speaker_emb.bias".
        size mismatch for speaker_emb.weight: copying a param with shape torch.Size([128, 512]) from checkpoint, the shape in current model is torch.Size([1, 128]).
```

or master:
```
RuntimeError: Error(s) in loading state_dict for DaftExprt:
        size mismatch for speaker_emb.weight: copying a param with shape torch.Size([128, 512]) from checkpoint, the shape in current model is torch.Size([5, 128]).
```

(both with speaker embedding set to "none", with DeepSpeaker I get a different error during preprocessing). Both errors suggest the model is expecting a speaker embedding of size 128, but it's loading an embedding of size 512 (ignoring the first dim n_speakers, I can fix that if needed).

**Comment by keonlee9420** [comment]
Hi @nmfisher , I just published v.1.0.1 (actually it was already there but not opened. I'm sorry for that), so can you please try again with it? I checked that it's working well.

**Comment by nmfisher** [comment]
Thanks @keonlee9420, same problem unfortunately:
```
(base) [hydroxide@AVINIUM Daft-Exprt-1.0.1]$ python3.7 prepare_align.py --dataset VCTK
100%|██████████████████████████████████████████████████████████████████████████████| 413/413 [00:45<00:00,  9.04it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:45<00:00, 45.71s/it]
(base) [hydroxide@AVINIUM Daft-Exprt-1.0.1]$ python3.7 preprocess.py --dataset VCTK                                  Load pre-defined validation set...
Processing Data ...
100%|██████████████████████████████████████████████████████████████████████████████| 826/826 [00:13<00:00, 59.67it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:13<00:00, 13.84s/it]
Computing statistic quantities ...
Total time: 0.22125391786344167 hours
(base) [hydroxide@AVINIUM Daft-Exprt-1.0.1]$ python3.7 synthesize.py --text "number one" --speaker_id p258 --restore_step 900000 --mode single --dataset VCTK --ref_audio ../number_one.wav
Traceback (most recent call last):
  File "synthesize.py", line 232, in <module>
    model = get_model(args, configs, device, train=False)
  File "/mnt/hdd_2tb/home/hydroxide/projects/Daft-Exprt/Daft-Exprt-1.0.1/utils/model.py", line 21, in get_model
    model.load_state_dict(ckpt["model"])
  File "/home/hydroxide/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DaftExprt:
        Unexpected key(s) in state_dict: "speaker_emb.bias".
        size mismatch for speaker_emb.weight: copying a param with shape torch.Size([128, 512]) from checkpoint, the shape in current model is torch.Size([1, 128]).
(base) [hydroxide@AVINIUM Daft-Exprt-1.0.1]$ md5sum output/ckpt/VCTK/900000.pth.tar
9c82496f6824df89f1a13082ebe606be  output/ckpt/VCTK/900000.pth.tar
(base) [hydroxide@AVINIUM Daft-Exprt-1.0.1]$ cat config/VCTK/preprocess.yaml
dataset: "VCTK"

path:
  corpus_path: "/mnt/sdd_512gb/data/audio_video/speech/VCTK"
  wav_tag: "mic1"
  wav_dir: "wav48_silence_trimmed"
  txt_dir: "txt"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data/VCTK"
  preprocessed_path: "./preprocessed_data/VCTK"

preprocessing:
  speaker_embedder: "none" # support 'none', 'DeepSpeaker'
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # always should be 'phoneme_level'
    normalization: True
  energy:
    feature: "phoneme_level" # always should be 'phoneme_level'
    normalization: True
  duration:
    log_duration: True

```

**Comment by nmfisher** [comment]
Update - I confirm that v1.0.1 does work with the DeepSpeaker embeddings. No luck on "none" though.

**Comment by keonlee9420** [comment]
Ah, the pre-trained model only supports `speaker_embedder: "DeepSpeaker"` since it is trained with that config. If you need to fine-tune the model with your own dataset, especially where the `speaker_embedder` should be 'none', you have to filter out speaker embedder from the shared checkpoint by the parameter name. I updated the code for you, so please try `speaker_embedder: "none"` in preprocess.yaml and `ignore_layers: ["speaker_emb"]` in train.yaml. There should be no error anymore.

**Comment by nmfisher** [comment]
Got it - thanks!
